# Generated by Django 4.2.11 on 2024-04-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_video_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
