# Generated by Django 4.2.11 on 2024-04-08 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_post_image_product_rename_post_video_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product', to='store.product', verbose_name='Comments'),
        ),
    ]
