# Generated by Django 4.2.11 on 2024-04-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Image', to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='video',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Video', to='store.product', verbose_name='Product'),
        ),
    ]
