# Generated by Django 4.2.11 on 2024-04-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Comments', to='blog.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Image', to='blog.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='video',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Video', to='blog.post', verbose_name='Post'),
        ),
    ]
