# Generated by Django 4.2.11 on 2024-04-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='title',
            field=models.CharField(default='sample', max_length=100),
        ),
    ]
